name: NGR validatie step 1

on:
  workflow_dispatch:
    tags:
    description: "Test scenario tags"
  schedule:
    - cron: "04 04 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Build with Maven step 0
        run: mvn clean --file pom.xml -Dkarate.options="--tags @step0" test
      - name: Build with Maven step 1
        run: mvn --file pom.xml -Dkarate.options="--tags @step1" test
      - name: Deploy 1
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
      - name: Deploy 2
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/surefire-reports
          keep_files: true
